swagger: "2.0"
info:
  title: Student Budget
  description: Rest Api model
  version: 1.0.0
tags:
- name: "User"
- name: "Transaction"
- name: "Account"
paths:
  /user:
    post:
      tags:
        - "User"
      summary: Add new User
      description: SQL
      parameters:
      - in: "body"
        name: "body"
        description: "New user that needs to be added to DB"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        '200':
          description: Succesfull operation
  /user/{email}:
    get:
      tags:
        - "User"
      summary: Finds user by Email
      description: SQL
      parameters:
        - name: "email"
          in: "path"
          description: "returns User if registered"
          required: true
          type: "string"
      responses:
        '200':
          description: Succesfull operation
          schema:
            $ref: "#/definitions/User"
            
  /transanctions/{month}:
    get:
      tags:
        - "Transaction"
      summary: Return all transaction of user in {month}
      description: SQL
      parameters:
        - name: "month"
          in: "path"
          description: "return transanctions in month"
          required: true
          type: "string"
      responses:
        '200':
          description: Succesfull operation
          schema:
            $ref: "#/definitions/Transaction"
  /transanctions:
    post:
      tags:
        - "Transaction"
      summary: Add new Transaction
      description: SQL
      parameters:
      - in: "body"
        name: "body"
        description: "Add new transaction"
        required: true
        schema:
          $ref: "#/definitions/Transaction"
      responses:
        '200':
          description: Succesfull operation
          
  /account:
    post:
      tags:
        - "Account"
      summary: Add new Account
      description: SQL
      parameters:
      - in: "body"
        name: "body"
        description: "Add new transaction"
        required: true
        schema:
          $ref: "#/definitions/Account"
      responses:
        '200':
          description: Succesfull operation
          
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      email:
        type: "string"
      password:
        type: "string"
        
  Transaction:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      Sum:
        type: "integer"
        format: "float"
      Category:
        type: "string"
      Timestamp:
        type: "string"
        format: "date-time"
      Email:
        type: "string"
        
  Account:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      iban:
        type: "string"
      
        